apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  traefik.toml: |
    logLevel = "DEBUG"
    defaultEntryPoints = ["https", "http"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
          entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
    [web]
    address = ":8080"
    [acme]
    email = "ops@andyet.net"
    storageFile = "/etc/acme/acme.json"
    entryPoint = "https"
    onDemand = true

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik
  labels:
    k8s-app: traefik
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        k8s-app: traefik
        kubernetes.io/cluster-service: "true"
    spec:
      terminationGracePeriodSeconds: 60
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      nodeSelector:
        traefik: "true"
      containers:
      - image: containous/traefik
        name: traefik
        imagePullPolicy: Always
        args:
        - --kubernetes
        - --kubernetes.endpoint=https://master-internal.talky.io
        ports:
        - containerPort: 80
          name: http
          hostPort: 80
        - containerPort: 443
          name: https
          hostPort: 443
        - containerPort: 8080
          name: api
          hostPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /etc/traefik
          name: traefik-config
          readOnly: true
        - mountPath: /etc/acme
          name: ssl-certs
      volumes:
      - name: traefik-config
        configMap:
          name: traefik-config
      - name: ssl-certs
        persistentVolumeClaim:
          claimName: acme