logLevel = "DEBUG"
defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[web]
address = ":8080"

[acme]
email = "ops@andyet.net"
storageFile = "/etc/acme/acme.json"
entryPoint = "https"
[[acme.domains]]
  main = "test.nodesecurity.io"

[kubernetes]
